### PR TITLE
initial simplification of CEN module

### PR DESCRIPTION
**Pull request by brianmori**
Hi @xiaozhu36 

I have made an initial PR to discuss the structure of the CEN. The README is not fully updated.

I believe the module can be simplified by putting all CEN related resources in one level only avoiding the different submodules as some resources are mandatory (as example the attachments) for the CEN to be used.
I will upload the VPC soon

### CODE REVIEW

**Comment by brianmori** [comment]
Hi @xiaozhu36

I have some tests in my local environment and it works. We are going to deploy it in our final environment in the coming days. In the meantime, please let me know if you have any feedback.

**Comment by jeanpierremilan** [comment]
+1

**Comment by supertom25** [comment]
+1

**Comment by supertom25** [comment]
👍

**Review by xiaozhu36 — APPROVED** [review]

**Pull request merged**
